[{
        "codigoFacultad": "FIRSTFAC000",
        "modulo": {
            "nombre": "Menú FIRSTFAC000",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1564524097306,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1564524097306,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC001",
        "modulo": {
            "nombre": "Menú FIRSTFAC001",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059011737,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562788541082,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC002",
        "modulo": {
            "nombre": "Menú FIRSTFAC002",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059143010,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787948068,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC003",
        "modulo": {
            "nombre": "Menú FIRSTFAC003",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059271977,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787908750,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC004",
        "modulo": {
            "nombre": "Menú FIRSTFAC004",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059368323,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787900203,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC005",
        "modulo": {
            "nombre": "Menú FIRSTFAC005",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059521207,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787917181,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC007",
        "modulo": {
            "nombre": "Menú FIRSTFAC007",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059626065,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787935185,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC009",
        "modulo": {
            "nombre": "Menú FIRSTFAC009",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059849142,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562788014717,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "FIRSTFAC010",
        "modulo": {
            "nombre": "Menú FIRSTFAC010",
            "codigoModulo": "COBRANZA_FIRST",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1551138283539,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308726159
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556059931875,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562788023392,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC000",
        "modulo": {
            "nombre": "Menú SECONDFAC000",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1549664805319,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1566951091069,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC001",
        "modulo": {
            "nombre": "Menú SECONDFAC001",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550252019276,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550252019276,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC002",
        "modulo": {
            "nombre": "Menú SECONDFAC002",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FSEGM",
        "estatus": "A",
        "fechaHoraAlta": 1550252058145,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550252058145,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC005",
        "modulo": {
            "nombre": "Menú SECONDFAC005",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255599786,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553553980969,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC006",
        "modulo": {
            "nombre": "Menú SECONDFAC006",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255642403,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553553988556,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC007",
        "modulo": {
            "nombre": "Menú SECONDFAC007",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255676951,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553553994681,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC008",
        "modulo": {
            "nombre": "Menú SECONDFAC008",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255713660,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554002087,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC009",
        "modulo": {
            "nombre": "Menú SECONDFAC009",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255750528,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554009238,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC010",
        "modulo": {
            "nombre": "Menú SECONDFAC010",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255812397,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554034194,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC011",
        "modulo": {
            "nombre": "Menú SECONDFAC011",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255862809,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1559071016215,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC014",
        "modulo": {
            "nombre": "Menú SECONDFAC014",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255972419,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554072364,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC015",
        "modulo": {
            "nombre": "Menú SECONDFAC015",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550255995256,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554172290,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC016",
        "modulo": {
            "nombre": "Menú SECONDFAC016",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256021941,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554183484,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC017",
        "modulo": {
            "nombre": "Menú SECONDFAC017",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256045400,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554193256,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC018",
        "modulo": {
            "nombre": "Menú SECONDFAC018",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256198187,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554205347,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC019",
        "modulo": {
            "nombre": "Menú SECONDFAC019",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256256378,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554222505,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC020",
        "modulo": {
            "nombre": "Menú SECONDFAC020",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256281673,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554233344,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC022",
        "modulo": {
            "nombre": "Menú SECONDFAC022",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256356883,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550256356883,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC023",
        "modulo": {
            "nombre": "Menú SECONDFAC023",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256379774,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550256379774,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC024",
        "modulo": {
            "nombre": "Menú SECONDFAC024",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256400332,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1553554278897,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC025",
        "modulo": {
            "nombre": "Menú SECONDFAC025",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256427386,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550256427386,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC026",
        "modulo": {
            "nombre": "Menú SECONDFAC026",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256451645,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550256451645,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC027",
        "modulo": {
            "nombre": "Menú SECONDFAC027",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1550256475843,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1550256475843,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC038",
        "modulo": {
            "nombre": "Menú SECONDFAC038",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1555432364582,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1555432482370,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC039",
        "modulo": {
            "nombre": "Menú SECONDFAC039",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1562779574656,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787152875,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC040",
        "modulo": {
            "nombre": "Menú SECONDFAC040",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1562780218085,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562780218085,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SECONDFAC041",
        "modulo": {
            "nombre": "Menú SECONDFAC041",
            "codigoModulo": "CAJA",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1549664653889,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308746357
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1562787443406,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562787443406,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC000",
        "modulo": {
            "nombre": "Menú THIRDFAC000",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1564526006655,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1564526006655,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC001",
        "modulo": {
            "nombre": "Menú THIRDFAC001",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556314356696,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562788160463,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC002",
        "modulo": {
            "nombre": "Menú THIRDFAC002",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1556928861692,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1563382276228,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC003",
        "modulo": {
            "nombre": "Menú THIRDFAC003",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557171591912,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1557334384328,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC004",
        "modulo": {
            "nombre": "Menú THIRDFAC004",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557171672634,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1557334378226,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC005",
        "modulo": {
            "nombre": "Menú THIRDFAC005",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557171818203,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1557334398190,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC006",
        "modulo": {
            "nombre": "Menú THIRDFAC006",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557171864895,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1565307464211,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC007",
        "modulo": {
            "nombre": "Menú THIRDFAC007",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557171984658,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1557334410582,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC008",
        "modulo": {
            "nombre": "Menú THIRDFAC008",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557172074773,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1565307284574,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC009",
        "modulo": {
            "nombre": "Menú THIRDFAC009",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557172133170,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1557334424239,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC010",
        "modulo": {
            "nombre": "Menú THIRDFAC010",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557172189934,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1564678039708,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC011",
        "modulo": {
            "nombre": "Menú THIRDFAC011",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557172254608,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1562788201077,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC012",
        "modulo": {
            "nombre": "Menú THIRDFAC012",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1557182493351,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1557334450584,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "THIRDFAC014",
        "modulo": {
            "nombre": "Menú THIRDFAC014",
            "codigoModulo": "COBRANZA_THIRD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1556308678434,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1556308678434
        },
        "tipoFacultad": "FPANT",
        "estatus": "A",
        "fechaHoraAlta": 1565294202267,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1565294202267,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    },
    {
        "codigoFacultad": "SEGMUEAGREGAR",
        "modulo": {
            "nombre": "Menú ",
            "codigoModulo": "CONFIG_SEGURIDAD",
            "estatus": "A",
            "empresaAlta": null,
            "fechaHoraAlta": 1508367614924,
            "usuarioUltimaModificacion": null,
            "personaUltimaModificacion": null,
            "empresaUltimaModificacion": 1,
            "fechaHoraUltimaModificacion": 1508367614924
        },
        "tipoFacultad": "FBTN",
        "estatus": "A",
        "fechaHoraAlta": 1520373712391,
        "empresaAlta": null,
        "fechaHoraUltimaModificacion": 1520373712391,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "cobranzaFacultad": null,
        "encriptaFacultad": null,
        "facultadesBoton": null,
        "caducidad": null
    }
]
//Menu
[
	{
		nombre_menu: "FIRST",
		id_menu: "FIRSTFAC000",
		options: [
			{
				"nombre": "Menú FIRSTFAC001",
				"codigoModulo": "COBRANZA_FIRST",
        "estatus": "A",
        "empresaAlta": null,
        "fechaHoraAlta": 1551138283539,
        "usuarioUltimaModificacion": null,
        "personaUltimaModificacion": null,
        "empresaUltimaModificacion": 1,
        "fechaHoraUltimaModificacion": 1556308726159
			}
		]
	}
]
